CREATE TABLE IF NOT EXISTS genre(
	Id SERIAL PRIMARY KEY, 
	Name VARCHAR(40) NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS musician(
	Id SERIAL PRIMARY KEY, 
	Name VARCHAR(40) NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS album(
	Id SERIAL PRIMARY KEY, 
	Name TEXT NOT NULL, 
	year INTEGER NOT NULL CHECK(year>1850 AND year<2022)  
);
CREATE TABLE IF NOT EXISTS track(
	Id SERIAL PRIMARY KEY, 
	Name TEXT NOT NULL, 
	Lenght NUMERIC(2,2), 
	Id_album INTEGER NOT NULL REFERENCES album(Id)
);
CREATE TABLE IF NOT EXISTS collection(
	Id SERIAL PRIMARY KEY, 
	Name TEXT NOT NULL, 
	year INTEGER NOT NULL CHECK(year>1850 AND year<2022) 
);


CREATE TABLE IF NOT EXISTS track_collection(
	Id_track INTEGER NOT NULL REFERENCES track(Id),
	Id_collection INTEGER NOT NULL REFERENCES collection(Id),
	CONSTRAINTS tc_pk PRIMARY KEY(Id_track, Id_collection)
);
CREATE TABLE IF NOT EXISTS musician_album(
	Id_musician INTEGER NOT NULL REFERENCES musician(Id),
	Id_album INTEGER NOT NULL REFERENCES album(Id),
	CONSTRAINTS ma_pk PRIMARY KEY(Id_musician, Id_album)
);
CREATE TABLE IF NOT EXISTS genre_musician(
	Id_genre INTEGER NOT NULL REFERENCES genre(Id),
	Id_musician INTEGER NOT NULL REFERENCES musician(Id),
	CONSTRAINTS gm_pk PRIMARY KEY(Id_genre, Id_musician)
);
